In [1]:
# Data understanding 

import pandas as pd
dataset_original=pd.read_csv("ai4i2020.csv") #copy of original dataset
dataset = dataset_original
dataset_original.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [2]:
dataset.shape

(10000, 14)

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  object
 2   Type                     10000 non-null  object
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64
 8   Machine failure          10000 non-null  int64
 9   TWF                      10000 non-null  int64
 10  HDF                      10000 non-null  int64
 11  PWF                      10000 non-null  int64
 12  OSF                      10000 non-null  int64
 13  RNF                      10000 non-null  int64
dtypes: float64(3), int64(9), object(2)
memory usage: 1.1+ MB

In [4]:
'''
1.	UID: unique identifier ranging from 1 to 10000
2.	product ID: consisting of a letter L, M, or H for low (50% of all products), medium (30%) and high (20%) as product quality variants and a variant-specific serial number
3.	type: just the product type L, M or H from column 2
4.	air temperature [K]: generated using a random walk process later normalized to a standard deviation of 2 K around 300 K
5.	process temperature [K]: generated using a random walk process normalized to a standard deviation of 1 K, added to the air temperature plus 10 K.
6.	rotational speed [rpm]: calculated from a power of 2860 W, overlaid with a normally distributed noise
7.	torque [Nm]: torque values are normally distributed around 40 Nm with a SD = 10 Nm and no negative values.
8.	tool wear [min]: The quality variants H/M/L add 5/3/2 minutes of tool wear to the used tool in the process.
9.	a 'machine failure' label that indicates, whether the machine has failed in this particular datapoint for any of the following failure modes are true.
'''

"\n1.\tUID: unique identifier ranging from 1 to 10000\n2.\tproduct ID: consisting of a letter L, M, or H for low (50% of all products), medium (30%) and high (20%) as product quality variants and a variant-specific serial number\n3.\ttype: just the product type L, M or H from column 2\n4.\tair temperature [K]: generated using a random walk process later normalized to a standard deviation of 2 K around 300 K\n5.\tprocess temperature [K]: generated using a random walk process normalized to a standard deviation of 1 K, added to the air temperature plus 10 K.\n6.\trotational speed [rpm]: calculated from a power of 2860 W, overlaid with a normally distributed noise\n7.\ttorque [Nm]: torque values are normally distributed around 40 Nm with a SD = 10 Nm and no negative values.\n8.\ttool wear [min]: The quality variants H/M/L add 5/3/2 minutes of tool wear to the used tool in the process.\n9.\ta 'machine failure' label that indicates, whether the machine has failed in this particular datapoint for any of the following failure modes are true.\n"

In [5]:
dataset.describe()

,UDI,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,5000.50000,300.004930,310.005560,1538.776100,39.986910,107.951000,0.033900,0.004600,0.011500,0.009500,0.009800,0.00190
std,2886.89568,2.000259,1.483734,179.284096,9.968934,63.654147,0.180981,0.067671,0.106625,0.097009,0.098514,0.04355
min,1.00000,295.300000,305.700000,1168.000000,3.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,2500.75000,298.300000,308.800000,1423.000000,33.200000,53.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,5000.50000,300.100000,310.100000,1503.000000,40.100000,108.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
75%,7500.25000,301.500000,311.100000,1612.000000,46.800000,162.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
max,10000.00000,304.500000,313.800000,2886.000000,76.600000,253.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000

In [6]:

# handling missing values

# their is no null values in this dataset 
dataset.isnull().sum()
dataset.isna().sum()

UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64

In [7]:
# Remove unwanted columns 
# drop the 'Product ID','UDI' - as it is unique product information - not required for model training 
dataset = dataset.drop(['Product ID','UDI'],axis=1)
dataset

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,M,298.8,308.4,1604,29.5,14,0,0,0,0,0,0
9996,H,298.9,308.4,1632,31.8,17,0,0,0,0,0,0
9997,M,299.0,308.6,1645,33.4,22,0,0,0,0,0,0
9998,H,299.0,308.7,1408,48.5,25,0,0,0,0,0,0
9999,M,299.0,308.7,1500,40.2,30,0,0,0,0,0,0

In [8]:
# Encoding - Preprocessing 
## convert categorical data into numerical data

from sklearn.preprocessing import LabelEncoder 
lable_encoder = LabelEncoder()
dataset['Type'] = lable_encoder.fit_transform(dataset['Type'])  
'''  # ordinal categorical data conversion using label encoder (ranking each data) 
L  -> 1
M  -> 2
H  -> 0
'''

'  # ordinal categorical data conversion using label encoder (ranking each data) \nL  -> 1\nM  -> 2\nH  -> 0\n'

In [9]:
dataset['Type'].value_counts()  # after

'''Type
L    6000
M    2997
H    1003
Name: count, dtype: int64'''   #before

'Type\nL    6000\nM    2997\nH    1003\nName: count, dtype: int64'

In [10]:

# handling class imbalance 

dataset['Machine failure'].value_counts()
# imbalanced data --- i will handle it via model training (class_weights) and evaluation metric (f1 score, precision , recall)

Machine failure
0    9661
1     339
Name: count, dtype: int64

# KEY NOTE: INITIAL PREPROCESSING 

KEY NOTE: INITIAL PREPROCESSING 

I started my predictive maintenance machine learning project by first understanding the dataset. I loaded the dataset and examined its shape, which contains 10,000 rows and 14 columns. Using the .info() function, I identified the data types and observed that UID and Product ID are unique identifier columns, Type is a categorical feature, and the remaining variables such as air temperature, process temperature, rotational speed, torque, and tool wear are numerical features. The target variable is Machine failure, which represents whether a failure has occurred. I then used descriptive statistics to understand the distribution, central tendency, and variability of the features. After that, I checked for missing values and found that the dataset has no null values, so no imputation was required. I removed irrelevant columns like UID and Product ID as they do not contribute to the prediction task. To handle the categorical variable Type, I applied encoding to convert it into a numerical format. Finally, I analyzed the target variable distribution and found that the dataset is imbalanced, which is an important consideration for model building. These steps formed the initial preprocessing phase before proceeding to exploratory data analysis.

In [11]:
dataset

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,2,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,1,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,1,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,1,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,1,298.2,308.7,1408,40.0,9,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2,298.8,308.4,1604,29.5,14,0,0,0,0,0,0
9996,0,298.9,308.4,1632,31.8,17,0,0,0,0,0,0
9997,2,299.0,308.6,1645,33.4,22,0,0,0,0,0,0
9998,0,299.0,308.7,1408,48.5,25,0,0,0,0,0,0
9999,2,299.0,308.7,1500,40.2,30,0,0,0,0,0,0